/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/user'
import { Route as IndexImport } from './routes/index'
import { Route as UserUserImport } from './routes/user/user'
import { Route as UserInputImport } from './routes/user/input'

// Create/Update Routes

const UserRoute = UserImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserRoute = UserUserImport.update({
  path: '/user',
  getParentRoute: () => UserRoute,
} as any)

const UserInputRoute = UserInputImport.update({
  path: '/input',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/user/input': {
      id: '/user/input'
      path: '/input'
      fullPath: '/user/input'
      preLoaderRoute: typeof UserInputImport
      parentRoute: typeof UserImport
    }
    '/user/user': {
      id: '/user/user'
      path: '/user'
      fullPath: '/user/user'
      preLoaderRoute: typeof UserUserImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UserRoute: UserRoute.addChildren({ UserInputRoute, UserUserRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user": {
      "filePath": "user.tsx",
      "children": [
        "/user/input",
        "/user/user"
      ]
    },
    "/user/input": {
      "filePath": "user/input.tsx",
      "parent": "/user"
    },
    "/user/user": {
      "filePath": "user/user.tsx",
      "parent": "/user"
    }
  }
}
ROUTE_MANIFEST_END */
